'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class thai
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Program04.thai", GetType(thai).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมายเลขจองตู้.
        '''</summary>
        Friend Shared ReadOnly Property booking_no() As String
            Get
                Return ResourceManager.GetString("booking_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เจ้าของตู้สินค้า.
        '''</summary>
        Friend Shared ReadOnly Property box_operator() As String
            Get
                Return ResourceManager.GetString("box_operator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to พนักงานตรวจสภาพ.
        '''</summary>
        Friend Shared ReadOnly Property checker() As String
            Get
                Return ResourceManager.GetString("checker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ผู้รับสินค้า.
        '''</summary>
        Friend Shared ReadOnly Property consignee() As String
            Get
                Return ResourceManager.GetString("consignee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมายเลขตู้สินค้า.
        '''</summary>
        Friend Shared ReadOnly Property container_no() As String
            Get
                Return ResourceManager.GetString("container_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ขนาด/ชนิด.
        '''</summary>
        Friend Shared ReadOnly Property container_type() As String
            Get
                Return ResourceManager.GetString("container_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ความเสียหาย.
        '''</summary>
        Friend Shared ReadOnly Property damage() As String
            Get
                Return ResourceManager.GetString("damage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่.
        '''</summary>
        Friend Shared ReadOnly Property date_() As String
            Get
                Return ResourceManager.GetString("date_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ใบตรวจรับสภาพตู้สินค้า.
        '''</summary>
        Friend Shared ReadOnly Property eir() As String
            Get
                Return ResourceManager.GetString("eir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ข้อยกเว้น.
        '''</summary>
        Friend Shared ReadOnly Property exception() As String
            Get
                Return ResourceManager.GetString("exception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เครื่องปั่นไฟ.
        '''</summary>
        Friend Shared ReadOnly Property genset_no() As String
            Get
                Return ResourceManager.GetString("genset_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รหัสสินค้าอันตราย.
        '''</summary>
        Friend Shared ReadOnly Property imo() As String
            Get
                Return ResourceManager.GetString("imo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property iso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รหัสมาตรฐาน.
        '''</summary>
        Friend Shared ReadOnly Property iso_code() As String
            Get
                Return ResourceManager.GetString("iso_code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property lcb1_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lcb1_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ทะเบียนรถ.
        '''</summary>
        Friend Shared ReadOnly Property licence() As String
            Get
                Return ResourceManager.GetString("licence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมายเลขทะเบียนรถ.
        '''</summary>
        Friend Shared ReadOnly Property license() As String
            Get
                Return ResourceManager.GetString("license", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ส่งตู้.
        '''</summary>
        Friend Shared ReadOnly Property liftoff() As String
            Get
                Return ResourceManager.GetString("liftoff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รับตู้.
        '''</summary>
        Friend Shared ReadOnly Property lifton() As String
            Get
                Return ResourceManager.GetString("lifton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลักษณะตู้เข้า-ออก.
        '''</summary>
        Friend Shared ReadOnly Property move() As String
            Get
                Return ResourceManager.GetString("move", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมายเหตุ.
        '''</summary>
        Friend Shared ReadOnly Property note() As String
            Get
                Return ResourceManager.GetString("note", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1) ห้ามลงจากรถขณะอยู่ในลานตู้สินค้า
        '''2) ห้ามมีผู้โดยสารติดเข้ามาในลานตู้สินค้า
        '''3) ห้ามสูบบุหรี่และทิ้งขยะในลานตู้สินค้า
        '''4) กรณีมีปัญหาติดขัดด้านเอกสารหรือเส้นทางให้ติดต่อเบอร์ 038-408600 ต่อ 1776.
        '''</summary>
        Friend Shared ReadOnly Property notice() As String
            Get
                Return ResourceManager.GetString("notice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่สั่ง.
        '''</summary>
        Friend Shared ReadOnly Property order_date() As String
            Get
                Return ResourceManager.GetString("order_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ท่าขนถ่าย.
        '''</summary>
        Friend Shared ReadOnly Property pod() As String
            Get
                Return ResourceManager.GetString("pod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมายเลขใบเสร็จ.
        '''</summary>
        Friend Shared ReadOnly Property receipt_no() As String
            Get
                Return ResourceManager.GetString("receipt_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมายเหตุ.
        '''</summary>
        Friend Shared ReadOnly Property remark() As String
            Get
                Return ResourceManager.GetString("remark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to หมายเลขผนึกตู้.
        '''</summary>
        Friend Shared ReadOnly Property seal_no() As String
            Get
                Return ResourceManager.GetString("seal_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สายการเดินเรือ.
        '''</summary>
        Friend Shared ReadOnly Property shpping_line() As String
            Get
                Return ResourceManager.GetString("shpping_line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ดูตัวเลขตำแหน่งตู้ที่เป็นสีเหลืองเท่านั้น.
        '''</summary>
        Friend Shared ReadOnly Property special_text() As String
            Get
                Return ResourceManager.GetString("special_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to อุณหภูมิ.
        '''</summary>
        Friend Shared ReadOnly Property temperature() As String
            Get
                Return ResourceManager.GetString("temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บริษัทรถ.
        '''</summary>
        Friend Shared ReadOnly Property truck_company() As String
            Get
                Return ResourceManager.GetString("truck_company", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เรือ.
        '''</summary>
        Friend Shared ReadOnly Property vessel() As String
            Get
                Return ResourceManager.GetString("vessel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เที่ยวเรือ.
        '''</summary>
        Friend Shared ReadOnly Property voy() As String
            Get
                Return ResourceManager.GetString("voy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to น้ำหนัก.
        '''</summary>
        Friend Shared ReadOnly Property weight() As String
            Get
                Return ResourceManager.GetString("weight", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
